#http://localhost:8080/baseDstu3/Patient?_pretty=true
#http://localhost:8080/baseDstu3/ValueSet?_pretty=true
#http://localhost:8080/baseDstu3/Patient/2341

#curl -H "Content-Type: application/json" -X POST -d '{ "resourceType": "Patient", "id": "32754", "meta": { "versionId": "50", "lastUpdated": "2017-11-14T10:24:22.403-05:00" }, "language": "zh-TW", "text": { "status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"> <table class=\"hapiPropertyTable\"> <tbody/> </table> </div>" } }' http://localhost:8080/baseDstu3/Patient



version: '2.0'

services:
   postgres:
      # Empty database
      # image: postgres:9.3
      # Database with DSTU3 example data
      image: jtmille3/postgres:latest
      #container_name: fhir_postgres
      restart: always
      ports:
         - 5432:5432  
#      networks:
#        vpcbr:
#            ipv4_address: 172.19.0.1
      #network_mode: host

         
      environment:
         - POSTGRES_DB=fhir
         - POSTGRES_USER=postgres
   fhir:
      image: jtmille3/hapi-fhir-dstu3-v2.5-postgres:latest
      restart: always
      ports:
         - 8080:8080
      environment:
         #- JAVA_OPTIONS=-Dpostgres.host=172.19.0.1
         #- JAVA_OPTIONS=-Dpostgres.host=0.0.0.0
         - JAVA_OPTIONS=-Dpostgres.host=postgres
         #- JAVA_OPTIONS=-Dpostgres.host=fhir_postgres
      links:
         - postgres
      depends_on:
         - postgres
      #command: ["./wait-for-it.sh"]
      
         #- fhir_post
      #network_mode: host
