#http://localhost:8080/baseDstu3/Patient?_pretty=true
#http://localhost:8080/baseDstu3/ValueSet?_pretty=true
#http://localhost:8080/baseDstu3/Patient/2341

#curl -H "Content-Type: application/json" -X POST -d '{ "resourceType": "Patient", "id": "32754", "meta": { "versionId": "50", "lastUpdated": "2017-11-14T10:24:22.403-05:00" }, "language": "zh-TW", "text": { "status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"> <table class=\"hapiPropertyTable\"> <tbody/> </table> </div>" } }' http://localhost:8080/baseDstu3/Patient



version: '2.1'

services:
   postgres:
      # Empty database
      # Database with DSTU3 example data
      image: jtmille3/postgres:latest
      restart: always
      ports:
         - 5432:5432
      environment:
         - POSTGRES_DB=fhir
         - POSTGRES_USER=postgres
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -p 5432 -u postgres"]
         interval: 3s
         timeout: 30s
         retries: 35

   strokeapp_db:
      image: postgres:alpine
      restart: always
      ports:
         - 5433:5433
      environment:
         POSTGRES_DB: strokeapp
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: password
         POSTGRES_PORT: 5433
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -p 5433 -u postgres"]
         interval: 3s
         timeout: 30s
         retries: 35
      #command: bash -c "sleep 10"

   fhir:
      image: jtmille3/hapi-fhir-dstu3-v2.5-postgres:latest
      restart: always
      ports:
         - 9080:8080
      environment:
         - JAVA_OPTIONS=-Dpostgres.host=postgres
      links:
         - postgres
      depends_on:
         postgres:
           condition: service_healthy


   web:
      image: iivanov8/strokeapp
      restart: always
      ports:
         - 8888:8888
      #environment:
      #   springDatasource: "jdbc:postgresql://strokeapp_db:5432/strokeapp"
      depends_on:
         strokeapp_db:
           condition: service_healthy
      #command: ["bash", "-c", "sleep 1"]
