#http://localhost:8080/baseDstu3/Patient?_pretty=true
#http://localhost:8080/baseDstu3/ValueSet?_pretty=true
#http://localhost:8080/baseDstu3/Patient/2341

#curl -H "Content-Type: application/json" -X POST -d '{ "resourceType": "Patient", "id": "32754", "meta": { "versionId": "50", "lastUpdated": "2017-11-14T10:24:22.403-05:00" }, "language": "zh-TW", "text": { "status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"> <table class=\"hapiPropertyTable\"> <tbody/> </table> </div>" } }' http://localhost:8080/baseDstu3/Patient



version: '2.0'

services:
   postgres:
      # Empty database
      # Database with DSTU3 example data
      image: jtmille3/postgres:latest
      restart: always
      ports:
         - 5432:5432
      environment:
         - POSTGRES_DB=fhir
         - POSTGRES_USER=postgres

   strokeapp_db:
      image: postgres:alpine
      restart: always
      ports:
         - 5433:5433
      environment:
         POSTGRES_DB: strokeapp
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: password
         POSTGRES_PORT: 5433
      #command: bash -c "sleep 10"

   fhir:
      image: jtmille3/hapi-fhir-dstu3-v2.5-postgres:latest
      restart: always
      ports:
         - 9080:8080
      environment:
         - JAVA_OPTIONS=-Dpostgres.host=postgres
      links:
         - postgres
      depends_on:
         - postgres

   web:
      image: iivanov8/strokeapp
      restart: always
      ports:
         - 8888:8888
      #environment:
      #   springDatasource: "jdbc:postgresql://strokeapp_db:5432/strokeapp"
      depends_on:
         - strokeapp_db
      #command: ["bash", "-c", "sleep 1"]

   start_database:
      image: dadarek/wait-for-dependencies
      depends_on:
        - postgres
        - strokeapp_db
      command: strokeapp_db:5433 postgres:5432

   start_fhir:
      image: dadarek/wait-for-dependencies
      depends_on:
        - postgres
        - strokeapp_db
        - fhir
      command: strokeapp_db:5433 postgres:5432 fhir:9080
